name: monaco
description: Private messaging platform for Moanark Council
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.2.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.0
  connectivity_plus: ^6.0.0
  permission_handler: ^10.4.3
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.2
  intl: ^0.18.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lint: ^2.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true